server {
    listen 80;
    server_name automationchallenge.cgi.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name automationchallenge.cgi.com;

    ssl_certificate /etc/nginx/certs/automationchallenge.cgi.com.pem;
    ssl_certificate_key /etc/nginx/certs/automationchallenge.cgi.com-key.pem;

    root /usr/share/nginx/html;
    index index.html;
}
